package co.kukurin.tasklist.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import co.kukurin.tasklist.dao.Tasks;

import co.kukurin.tasklist.dao.TasksDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tasksDaoConfig;

    private final TasksDao tasksDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tasksDaoConfig = daoConfigMap.get(TasksDao.class).clone();
        tasksDaoConfig.initIdentityScope(type);

        tasksDao = new TasksDao(tasksDaoConfig, this);

        registerDao(Tasks.class, tasksDao);
    }
    
    public void clear() {
        tasksDaoConfig.getIdentityScope().clear();
    }

    public TasksDao getTasksDao() {
        return tasksDao;
    }

}
